# Settings

WIDTH, HEIGHT = 800, 630
FPS = 60

# Wall
WALL_TICKNS = 5
WALL_HLN = WIDTH
WALL_VLN = HEIGHT
W_UX, W_UY = 0, 0
W_DX, W_DY = 0, HEIGHT - WALL_TICKNS
W_LX, W_LY = 0, 0
W_RX, W_RY = WIDTH - WALL_TICKNS, 0

# Color 
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Paddle
PAD_WIDTH, PAD_HEIGHT = 100, 12
PAD_SPEED = 10
PAD_DISX = 30
PAD_X = WIDTH/2 - PAD_WIDTH/2
PAD_Y= HEIGHT - PAD_DISX
