# Settings
FPS = 60

# Brick
BRICK_W = 8
BRICK_H = 4
BRICK_HMX = 10
BRICK_LN = 70
BRICK_TN = 30
EDGE_LN = 5

#XDXD
PLAY_HEIGHT = 400
DATA_WIDTH = 50 
TITLE_HEIGHT = 0

# Wall
WALL_TICKNS = 5
WALL_HLN = BRICK_W*BRICK_LN + (BRICK_W+1)*EDGE_LN + 2*(WALL_TICKNS+DATA_WIDTH)
WALL_VLN = BRICK_H*BRICK_TN + (BRICK_HMX+1)*EDGE_LN + PLAY_HEIGHT
W_UX, W_UY = 0, TITLE_HEIGHT
W_DX, W_DY = 0, WALL_VLN - WALL_TICKNS + TITLE_HEIGHT
W_LX, W_LY = DATA_WIDTH, + TITLE_HEIGHT
W_RX, W_RY = WALL_HLN - DATA_WIDTH - WALL_TICKNS, TITLE_HEIGHT

# Color 
WIDTH, HEIGHT = WALL_HLN, WALL_VLN + TITLE_HEIGHT
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

# Paddle
PAD_WIDTH, PAD_HEIGHT = 100, 12
PAD_SPEED = 10
PAD_DISX = 30
PAD_X = WIDTH/2 - PAD_WIDTH/2
PAD_Y= HEIGHT - PAD_DISX

# Ball
BALL_X, BALL_Y = PAD_X + PAD_WIDTH/2, HEIGHT - PLAY_HEIGHT
BALL_SPEED = 6
BALL_RADIUS = 6

